import { DrinkPreset } from '../types';

export const DEFAULT_DRINKS: DrinkPreset[] = [
  {
    id: 'beer-500',
    name: 'Bira (500 ml)',
    icon: '🍺',
    ml: 500,
    percent: 5.0,
    category: 'beer',
    description: 'Standart kutu/şişe bira (%5.0 alkol)',
  },
  {
    id: 'beer-330',
    name: 'Bira (330 ml)',
    icon: '🍺',
    ml: 330,
    percent: 5.0,
    category: 'beer',
    description: 'Küçük kutu bira (%5.0 alkol)',
  },
  {
    id: 'beer-strong',
    name: 'Kırmızı/Sert Bira',
    icon: '🍻',
    ml: 500,
    percent: 7.5,
    category: 'beer',
    description: 'Yüksek alkollü bira (%7.5 - 8.0)',
  },
  {
    id: 'wine',
    name: 'Şarap (150 ml)',
    icon: '🍷',
    ml: 150,
    percent: 12.5,
    category: 'wine',
    description: '1 Kadeh kırmızı veya beyaz şarap',
  },
  {
    id: 'raki-duble',
    name: 'Rakı (Duble 80 ml)',
    icon: '🍶',
    ml: 80,
    percent: 45.0,
    category: 'raki',
    description: 'Duble rakı (8 cl, %45 alkol)',
  },
  {
    id: 'raki-tek',
    name: 'Rakı (Tek 40 ml)',
    icon: '🍶',
    ml: 40,
    percent: 45.0,
    category: 'raki',
    description: 'Tek rakı (4 cl, %45 alkol)',
  },
  {
    id: 'whiskey',
    name: 'Viski (50 ml)',
    icon: '🥃',
    ml: 50,
    percent: 40.0,
    category: 'spirit',
    description: 'Tek ölçü malt veya harman viski',
  },
  {
    id: 'vodka',
    name: 'Votka (50 ml)',
    icon: '🍸',
    ml: 50,
    percent: 40.0,
    category: 'spirit',
    description: 'Sek veya kokteyl içi tek ölçü',
  },
  {
    id: 'tequila',
    name: 'Tekila (Shot 35 ml)',
    icon: '🎯',
    ml: 35,
    percent: 40.0,
    category: 'spirit',
    description: '1 Shot tekila (%40)',
  },
  {
    id: 'gin',
    name: 'Cin Tonik (50 ml)',
    icon: '🍹',
    ml: 50,
    percent: 40.0,
    category: 'spirit',
    description: '5 cl Cin + Tonik',
  },
  {
    id: 'cocktail',
    name: 'Kokteyl (200 ml)',
    icon: '🍸',
    ml: 200,
    percent: 12.0,
    category: 'cocktail',
    description: 'Mojito, Aperol Spritz, Margarita vb.',
  },
  {
    id: 'champagne',
    name: 'Şampanya (150 ml)',
    icon: '🍾',
    ml: 150,
    percent: 12.0,
    category: 'wine',
    description: 'Köpüklü şarap veya şampanya',
  },
];
